#!/usr/bin/env perl
#
#
#This waits untill I have a network connection, then opens IRC
my $good = "0% packet loss";
my $ping = "connect: Network is unreachable";
print ("checking for internet\n");
while($good =~ $ping) {
    $ping = `ping 8.8.8.8 -c 1`;
    print("$ping\n");
    sleep 1
}
print("connected to internet\n");
system('termite -e "mosh home -- tmux a -t IRC"');
