#!/usr/bin/env python

#This program is a notification system.
#run this as 
#"commandToRun; notifi Subject Message"
#or
#"commandToRun; notifi Subject"
#after the command is run this will send a email to me
#If you are not me, please change the email "toaddrs". 
import smtplib
import sys
import os
import socket


#thos sets the working directory to ~/dotfiles/scripts
#or wherever "notifi" exists in the filesystem
os.chdir(os.path.dirname(__file__))
print(os.getcwd())

hostname = socket.gethostname()
fromaddr = 'merfeldalertbot@gmail.com'
toaddrs  = 'kmerfeld1@gmail.com'
msg = "Subject: This is a notice.\nThis came from " + hostname

#check if an argument is given
length = (len(sys.argv))
if length > 2:
    msg = ("Subject: " + sys.argv[1] +"\n" + sys.argv[2])
elif (length> 1):
    msg = "Subject: " + sys.argv[1]


#Create file if it doesnt exist
if not os.path.exists("notifi-pass"):
    open("notifi-pass", 'w').close() 

# Credentials
f = open("notifi-pass","r+")
username = 'merfeldalertbot@gmail.com'
password = f.readline()
f.close

#Reads in password
if password == "":
    f = open("notifi-pass","w+")
    password = input("Enter MerfAlertBot password: ")
    f.write(password)
    f.close

# The actual mail send
server = smtplib.SMTP('smtp.gmail.com:587')
server.starttls()
server.login(username,password)
server.sendmail(fromaddr, toaddrs, msg)
server.quit()
server.sendmail
