#!/usr/bin/env perl

# This little script just toggles my touchpad


# read in the current status
my $synclient = `synclient`;
my @sync = split("\n", $synclient);
my @touchpad = grep(/TouchpadOff/, @sync);

# toggle
if ($touchpad[0] =~ "1") 
{
    `synclient TouchpadOff=0`;
}
else
{
    `synclient TouchpadOff=1`;
}
